[package]
name = "ps-algorithm"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["kiwiyou <kiwiyou@kiwiyou.dev>"]

[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.4"

[[bench]]
name = "graph"
harness = false
